### ISSUE TITLE
Überraschungsbox launchen

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#45]
+ LP ist noch nicht fertig programmiert
+ Produkte sind noch nicht definiert und zugewiesen
+ Es gibt noch keine Werbemittel/Banner

**Comment by mottermayr** [comment]
**Spätestens am Dienstag, 14.02. muss der Schmarrn online sein.**

**Comment by mottermayr** [comment]
Kann man das Produkt "Small" einfach kopieren?? Damit man jeweils nur 1 Größe hinzufügen muss??

**Comment by ckreuter** [comment]
Nein leider varianten werden nicht kopiert !Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [MiracleWoman/hq] Überraschungsbox launchen (#45)Von: mottermayr An: MiracleWoman/hq Cc: ckreuter ,Assign Kann man das Produkt "Small" einfach kopieren?? Damit man jeweils nur 1 Größe hinzufügen muss??

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MiracleWoman/hq","title":"MiracleWoman/hq","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MiracleWoman/hq"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mottermayr in #45: Kann man das Produkt \"Small\" einfach kopieren?? Damit man jeweils nur 1 Größe hinzufügen muss??"}],"action":{"name":"View Issue","url":"https://github.com/MiracleWoman/hq/issues/45#issuecomment-278895251"}}}
